# OCR Server Configuration
# All settings are optional - the server will use sensible defaults

server:
  host: '0.0.0.0'          # Bind to all interfaces (use '127.0.0.1' for localhost only)
  port: 8080               # Port to listen on
  debug: false             # Enable Flask debug mode (don't use in production)

ocr:
  languages: ['uk', 'en']  # Languages to load (Ukrainian and English)
  detail: 0                # 0 = text only, 1 = text with coordinates
  paragraph: true          # Group text into paragraphs
  workers: 0               # Number of worker processes (0 = auto)

upload:
  max_file_size: 16777216  # Maximum file size in bytes (16MB)
  allowed_extensions:      # Allowed file extensions
    - 'png'
    - 'jpg'
    - 'jpeg'
    - 'webp'
    - 'tiff'
    - 'bmp'
  temp_cleanup: true       # Clean up temporary files after processing

cors:
  enabled: true            # Enable CORS for cross-origin requests
  origins: '*'             # Allowed origins (* = all, or specify list like ['http://localhost:5000'])

logging:
  level: 'INFO'            # Logging level (DEBUG, INFO, WARNING, ERROR)
  save_requests: false     # Save processed images and results for debugging
  request_log_dir: './ocr_logs'  # Directory to save request logs (if save_requests is true)